spring.application.name=chat-demo


#Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=deepseek-r1:1.5b
#spring.ai.ollama.embedding.options.model=shaw/dmeta-embedding-zh:latest

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/chat_db?allowPublicKeyRetrieval=true&useSSL-false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-Plus
mybatis-plus.mapper-locations=classpath:/mapper/*.xm1
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.com.example.chat=DEBUG